apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: {{ .Values.computeClassName }}
spec:
  nodePoolAutoCreation:
    enabled: true

  priorities:
    - machineType: g4-standard-48
      gpu:
        type: nvidia-rtx-pro-6000
        count: 1
        driverVersion: default
      spot: false

    - machineType: g2-standard-12
      gpu:
        type: nvidia-l4
        count: 1
        driverVersion: default
      spot: true

    - machineType: g2-standard-12
      gpu:
        type: nvidia-l4
        count: 1
        driverVersion: default
      spot: false

  whenUnsatisfiable: ScaleUpAnyway

  activeMigration:
    optimizeRulePriority: true
