apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: health-check-policy
  namespace: {{ .Values.inferenceNamespace }}
spec:
  targetRef:
    group: "networking.gke.io"
    kind: GCPInferencePoolImport
    name: {{ .Values.inferencePoolName }}
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
        port: 8000
